version: '3.2'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./docker/production/nginx.conf:/etc/nginx/conf.d/default.conf
      - /dev/null:/var/www/html/index.php
      - public-files:/var/www/html/files
      - assets:/var/www/html/assets
    ports:
     - "80:80"
    depends_on:
      - mapasculturais
    links:
      - mapasculturais
  
  mapasculturais:
    env_file:
      - .env
    image: rafaelsdomingos/mapacultural:latest
    restart: unless-stopped
    volumes:
      - ./.env:/.env
      - assets:/var/www/html/assets
      - public-files:/var/www/html/files
      - private-files:/var/www/var/private-files
      - saas-files:/var/www/var/saas-files
      - sessions:/var/www/var/sessions
      - logs:/var/www/var/logs
      - ./docker/production/config.d:/var/www/config/prod.d
    links:
      - db
      - redis
      - sessions
    environment:
      - REDIS_CACHE=redis
      - SESSIONS_SAVE_PATH=tcp://sessions:6379

    depends_on:
      - db
      - redis
      - sessions

  redis:
    image: redis:6
    command: --maxmemory 1256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
 
  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - sessions:/data

  db:
    image: postgis/postgis:14-master
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    
# Configuração dos volumes
volumes:
  assets:
  db-data:
  logs:
  private-files:
  public-files:
  saas-files:
  sessions:


## Em ambiente de homologação pode ser uma boa ideia utilizar o mailhog para testar 
## o envio de emails e também prevenir que emails de tete sejam disparados acidentalmente 
## para os usuários no caso de o ambiente de homologação utilizar um banco de dados cópia
## de produção

  # mailhog: 
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"
